"""Add knowledge models and pgvector

Revision ID: 0413b862cc85
Revises: b4f812345678
Create Date: 2026-09-24 17:46:24.823951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0413b862cc85'
down_revision: Union[str, Sequence[str], None] = 'b4f812345678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_evidence', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('student_evidence', 'evidence_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_evidence', 'evidence_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('student_evidence', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
