"""Add industry assessment models

Revision ID: 31dd2920bcf0
Revises: d4a1d697a232
Create Date: 2026-09-24 21:36:07.978627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31dd2920bcf0'
down_revision: Union[str, Sequence[str], None] = 'd4a1d697a232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('work_mode', sa.String(), nullable=True),
    sa.Column('eligibility', sa.String(), nullable=True),
    sa.Column('experience_requirement', sa.String(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assessment_required', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['target_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_jobs_id'), 'company_jobs', ['id'], unique=False)
    op.create_table('hr_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['target_companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_hr_profiles_id'), 'hr_profiles', ['id'], unique=False)
    op.create_table('company_job_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('required_level', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['company_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_job_skills_id'), 'company_job_skills', ['id'], unique=False)
    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assessment_attempt_id', sa.Integer(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_attempt_id'], ['assessment_attempts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['company_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_applications_id'), 'job_applications', ['id'], unique=False)
    op.add_column('assessment_attempts', sa.Column('overall_score', sa.Float(), nullable=True))
    op.add_column('assessment_attempts', sa.Column('skill_wise_scores', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('assessment_attempts_assessment_id_fkey'), 'assessment_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'assessment_attempts', 'assessments', ['assessment_id'], ['id'], ondelete='CASCADE')
    op.add_column('assessment_questions', sa.Column('skill_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assessment_questions', 'skills', ['skill_id'], ['id'])
    op.add_column('assessments', sa.Column('company_job_id', sa.Integer(), nullable=True))
    op.add_column('assessments', sa.Column('total_marks', sa.Integer(), nullable=True))
    op.add_column('assessments', sa.Column('passing_criteria', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'assessments', 'company_jobs', ['company_job_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('user_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.drop_column('assessments', 'passing_criteria')
    op.drop_column('assessments', 'total_marks')
    op.drop_column('assessments', 'company_job_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'assessment_questions', type_='foreignkey')
    op.drop_column('assessment_questions', 'skill_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'assessment_attempts', type_='foreignkey')
    op.create_foreign_key(op.f('assessment_attempts_assessment_id_fkey'), 'assessment_attempts', 'assessments', ['assessment_id'], ['id'])
    op.drop_column('assessment_attempts', 'skill_wise_scores')
    op.drop_column('assessment_attempts', 'overall_score')
    op.drop_index(op.f('ix_job_applications_id'), table_name='job_applications')
    op.drop_table('job_applications')
    op.drop_index(op.f('ix_company_job_skills_id'), table_name='company_job_skills')
    op.drop_table('company_job_skills')
    op.drop_index(op.f('ix_hr_profiles_id'), table_name='hr_profiles')
    op.drop_table('hr_profiles')
    op.drop_index(op.f('ix_company_jobs_id'), table_name='company_jobs')
    op.drop_table('company_jobs')
    # ### end Alembic commands ###
