"""Add roadmap models

Revision ID: 36e7c127a832
Revises: 0413b862cc85
Create Date: 2026-09-24 18:41:30.465757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e7c127a832'
down_revision: Union[str, Sequence[str], None] = '0413b862cc85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('target_company_id', sa.Integer(), nullable=True),
    sa.Column('target_role_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['target_company_id'], ['target_companies.id'], ),
    sa.ForeignKeyConstraint(['target_role_id'], ['career_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmaps_id'), 'roadmaps', ['id'], unique=False)
    op.create_index(op.f('ix_roadmaps_student_id'), 'roadmaps', ['student_id'], unique=False)
    op.create_table('roadmap_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roadmap_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('step_order', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('objective', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('estimated_duration', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('resource_references', sa.JSON(), nullable=True),
    sa.Column('practice_task', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_steps_id'), 'roadmap_steps', ['id'], unique=False)
    op.create_index(op.f('ix_roadmap_steps_roadmap_id'), 'roadmap_steps', ['roadmap_id'], unique=False)
    op.create_index(op.f('ix_roadmap_steps_skill_id'), 'roadmap_steps', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmap_steps_skill_id'), table_name='roadmap_steps')
    op.drop_index(op.f('ix_roadmap_steps_roadmap_id'), table_name='roadmap_steps')
    op.drop_index(op.f('ix_roadmap_steps_id'), table_name='roadmap_steps')
    op.drop_table('roadmap_steps')
    op.drop_index(op.f('ix_roadmaps_student_id'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_id'), table_name='roadmaps')
    op.drop_table('roadmaps')
    # ### end Alembic commands ###
