"""Add job application unique constraint

Revision ID: 7318f102bbb4
Revises: 31dd2920bcf0
Create Date: 2026-09-24 21:39:42.582331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7318f102bbb4'
down_revision: Union[str, Sequence[str], None] = '31dd2920bcf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_job_student', 'job_applications', ['job_id', 'student_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_job_student', 'job_applications', type_='unique')
    # ### end Alembic commands ###
