"""Add gems models

Revision ID: 7d6b92f494c7
Revises: 36e7c127a832
Create Date: 2026-09-24 19:01:07.481664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d6b92f494c7'
down_revision: Union[str, Sequence[str], None] = '36e7c127a832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gems_daily_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('roadmap_id', sa.Integer(), nullable=True),
    sa.Column('plan_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gems_daily_plans_id'), 'gems_daily_plans', ['id'], unique=False)
    op.create_index(op.f('ix_gems_daily_plans_plan_date'), 'gems_daily_plans', ['plan_date'], unique=False)
    op.create_index(op.f('ix_gems_daily_plans_roadmap_id'), 'gems_daily_plans', ['roadmap_id'], unique=False)
    op.create_index(op.f('ix_gems_daily_plans_student_id'), 'gems_daily_plans', ['student_id'], unique=False)
    op.create_table('gems_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_plan_id', sa.Integer(), nullable=True),
    sa.Column('roadmap_step_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('task_type', sa.String(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('resource_references', sa.JSON(), nullable=True),
    sa.Column('completion_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['daily_plan_id'], ['gems_daily_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roadmap_step_id'], ['roadmap_steps.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gems_tasks_daily_plan_id'), 'gems_tasks', ['daily_plan_id'], unique=False)
    op.create_index(op.f('ix_gems_tasks_id'), 'gems_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_gems_tasks_scheduled_date'), 'gems_tasks', ['scheduled_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gems_tasks_scheduled_date'), table_name='gems_tasks')
    op.drop_index(op.f('ix_gems_tasks_id'), table_name='gems_tasks')
    op.drop_index(op.f('ix_gems_tasks_daily_plan_id'), table_name='gems_tasks')
    op.drop_table('gems_tasks')
    op.drop_index(op.f('ix_gems_daily_plans_student_id'), table_name='gems_daily_plans')
    op.drop_index(op.f('ix_gems_daily_plans_roadmap_id'), table_name='gems_daily_plans')
    op.drop_index(op.f('ix_gems_daily_plans_plan_date'), table_name='gems_daily_plans')
    op.drop_index(op.f('ix_gems_daily_plans_id'), table_name='gems_daily_plans')
    op.drop_table('gems_daily_plans')
    # ### end Alembic commands ###
