"""Add student GEMS preferences

Revision ID: d4a1d697a232
Revises: 7d6b92f494c7
Create Date: 2026-09-24 19:54:45.905525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4a1d697a232'
down_revision: Union[str, Sequence[str], None] = '7d6b92f494c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('gems_enabled', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('gems_reminder_enabled', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('gems_reminder_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'gems_reminder_time')
    op.drop_column('students', 'gems_reminder_enabled')
    op.drop_column('students', 'gems_enabled')
    # ### end Alembic commands ###
